- hosts: linux
  become: true

  vars:
    jobids: []

  tasks:

    - name: Ignore Failure
      command: /bin/false
      ignore_errors: yes

    - name: Fail only if return code is not 2
      shell: echo 2
      register: result
      failed_when: result.stdout != "2"


    - name: Task1
      command: /bin/sleep 5
      when: ansible_hostname == 'centos1'
      async: 10
      poll: 0
      register: result1

