- hosts: linux
  become: true

  tasks:
    - name: Configure the Servers
      copy:
        content: "Welcomessss to {{item}} Linux server"
        dest: /etc/motd1
      notify: MOTD Change
      with_items:
        - Ubuntu
        - CentOS

      when: ansible_distribution == item


  handlers:
    - name: MOTD Change
      debug:
        msg: "The MOTD changed"