
- hosts: linux
  become: true

  vars:
    motd_centos: "Welcome to CentOS Linux Server"
    motd_ubuntu: "Welcome to the Ubuntu Linux Server"

  tasks:
    - name: Configure the CentOS Server
      copy:
        content: "Welcome to {{item}} Linux server"
        dest: /etc/motd
      notify: MOTD Change
      with_items:
        -Ubuntu
        -CentOs

      when: ansible_distribution == item


  handlers:
    - name: MOTD Change
      debug:
        msg: "The MOTD changed"